// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjp1r41Mn3jh9rRaEDp4B7RX91AczvEpQ',
    appId: '1:376489192496:web:241a6ace6cd83a3dd651f5',
    messagingSenderId: '376489192496',
    projectId: 'todolist-3299a',
    authDomain: 'todolist-3299a.firebaseapp.com',
    storageBucket: 'todolist-3299a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyKKQNPWRH_-9AIkyvJdSUpNUZVRJmmtI',
    appId: '1:376489192496:android:a4c907aab397a267d651f5',
    messagingSenderId: '376489192496',
    projectId: 'todolist-3299a',
    storageBucket: 'todolist-3299a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_vaJG3r3h7jlKxEbQR3VVZTGdP70rgc',
    appId: '1:376489192496:ios:b2a0474fbf99c898d651f5',
    messagingSenderId: '376489192496',
    projectId: 'todolist-3299a',
    storageBucket: 'todolist-3299a.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk_vaJG3r3h7jlKxEbQR3VVZTGdP70rgc',
    appId: '1:376489192496:ios:b2a0474fbf99c898d651f5',
    messagingSenderId: '376489192496',
    projectId: 'todolist-3299a',
    storageBucket: 'todolist-3299a.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjp1r41Mn3jh9rRaEDp4B7RX91AczvEpQ',
    appId: '1:376489192496:web:a07728e609929272d651f5',
    messagingSenderId: '376489192496',
    projectId: 'todolist-3299a',
    authDomain: 'todolist-3299a.firebaseapp.com',
    storageBucket: 'todolist-3299a.appspot.com',
  );
}
